@ShoppingList.NathanJenner.Server_HostAddress = http://localhost:5230

### Get all shopping items
GET {{ShoppingList.NathanJenner.Server_HostAddress}}/api/items/
Accept: application/json

###

### Create a new shopping item
POST {{ShoppingList.NathanJenner.Server_HostAddress}}/api/items/
Content-Type: application/json

{
    "name": "Milk",
    "quantity": 2
}

###

### Update a shopping item
PUT {{ShoppingList.NathanJenner.Server_HostAddress}}/api/items/1
Content-Type: application/json

{
    "name": "Milk",
    "quantity": 3
}

###

### Delete a shopping item
DELETE {{ShoppingList.NathanJenner.Server_HostAddress}}/api/items/1

###

### Toggle purchased state of a shopping item
PATCH {{ShoppingList.NathanJenner.Server_HostAddress}}/api/items/1/toggle

###

